---
# Configuration file that will be used when generating a new pod from gitpod.io, this also sets up the IDE for further Dev.

tasks:
  - before: sdk use java 17.0.7.fx-zulu
    init: ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run Recipies app

vscode:
  extensions:
    - pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-initializr
