---
# Configuration file that will be used when generating a new pod from gitpod.io, this also sets up the IDE for further Dev.

tasks:    
  - name: 🛠️ Set up Java and Run app
    command: |
      sdk default java 17.0.7.fx-zulu
      # ./mvnw clean install -U -DskipTests
      # ./mvnw spring-boot:run

vscode:
  extensions:
    - pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-initializr
